#!/usr/bin/env node
/* Generate data/packs-bundle.js — a single committed global (OBOL.packData) from the
 * vendored obol-local pack JSONs, so packs load over file:// and http with no fetch and
 * no runtime build. Re-run after editing data/packs/*.json:  node tools/build-packs.js
 */
'use strict';
const fs = require('fs');
const path = require('path');

const PACKS_DIR = path.join(__dirname, '..', 'data', 'packs');
const OUT = path.join(__dirname, '..', 'data', 'packs-bundle.js');

// Load order = obol-local PACK_NAMES (planner) + the non-action data packs used by
// findings/fingerprints/exploits/scripts references.
const ACTION_PACKS = [
  'ad_2026_09', 'web_2026_09', 'recon_2026_09',
  'linux_privesc_2026_09', 'windows_privesc_2026_09',
  'obol_local_pivot_2026_09', 'obol_flag_hunt_2026_09',
  'findings_checks_2026_09', 'credential_access_2026_09',
  'web_exploit_checks_2026_09', 'database_2026_09',
  'cracking_2026_09', 'pivoting_2026_09', 'shells_2026_09',
];
const DATA_PACKS = [
  'findings_catalog_2026_09', 'web_fingerprints_2026_09',
  'known_exploits_2026_09', 'cisa_kev_2026_09', 'scripts_2026_09',
];

const data = {};
let actionCount = 0;
[].concat(ACTION_PACKS, DATA_PACKS).forEach((name) => {
  const p = path.join(PACKS_DIR, name + '.json');
  if (!fs.existsSync(p)) { console.warn('missing pack: ' + name); return; }
  const json = JSON.parse(fs.readFileSync(p, 'utf8'));
  data[name] = json;
  if (Array.isArray(json.actions)) actionCount += json.actions.length;
});

const banner = '/*! obol data — packs-bundle.js — GENERATED by tools/build-packs.js. Do not edit by hand.\n'
  + ' * Source: data/packs/*.json (vendored from obol-local). ' + Object.keys(data).length
  + ' packs, ' + actionCount + ' actions. */\n';

const body = '(function (root) {\n'
  + '  "use strict";\n'
  + '  var OBOL = root.OBOL = root.OBOL || {};\n'
  + '  OBOL.packData = ' + JSON.stringify(data) + ';\n'
  + '  OBOL.ACTION_PACKS = ' + JSON.stringify(ACTION_PACKS) + ';\n'
  + '  OBOL.DATA_PACKS = ' + JSON.stringify(DATA_PACKS) + ';\n'
  + '})(typeof globalThis !== "undefined" ? globalThis : this);\n';

fs.writeFileSync(OUT, banner + body);
console.log('Wrote ' + OUT + ' (' + Object.keys(data).length + ' packs, ' + actionCount + ' actions, '
  + (fs.statSync(OUT).size / 1024).toFixed(1) + ' KB).');
